---
title: "final exam"
author: "beverly chigarira"
date: "11/27/2020"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r}
#Question 1
Lungdata =read.csv("LungCapData.csv")

```

```{r}
#splitting data into training and testing set
#1(a)
set.seed(1234)
split=sample(2,nrow(Lungdata),replace = TRUE,prob = c(0.8,0.2))
training=Lungdata[split==1, ]
testing=Lungdata[split==2, ]
head(training)
head(testing)

```

```{r}
#1b  Using the training data
#fit a multiple regression line using the training data
# Multiple Linear Regression Example
fit <- lm(LungCap ~ Age + Height + Smoke + Gender, data=training)
summary(fit) # show results


```

```{r}
coefficients(fit)
```
```{r}
#Therefore the equation is :
#y = -11.37554 + 0.16141(Age) + 0.26428(Height) - 0.56596(Smoke) +  0.34012(Gender)
```


```{r}
#1c
#Testing the validity of the model using testing data
prediction = predict( fit, testing, type ="response")
head(prediction)
```

```{r}
head(testing)
#str(testing)
```
```{r}
str(Lungdata)
```
```{r}
#check value for male and female

#gendervalue =Lungdata$NGender= as.numeric(Lungdata$Gender)
#gendervalue
```

```{r}
#1d 
#Gender = male(1), smoke=yes(2), height= 55.5, Age=33
y1 = -11.37554 + 0.16141*(33) + 0.26428*(55.5) - 0.56596*(2) +  0.34012*(1)
y1
```

```{r}
#Gender = female, smoke=yes, height= 55.5, Age=33
y2 = -11.37554 + 0.16141*(33) + 0.26428*(55.5) - 0.56596*(2) +  0.34012*(2)
y2
```

```{r}
#Gender = male, smoke=no, height= 55.5, Age=33
y3 = -11.37554 + 0.16141*(33) + 0.26428*(55.5) - 0.56596*(1) +  0.34012*(1)
y3
```

```{r}
#Gender = female, smoke=no, height= 55.5, Age=33
y4 = -11.37554 + 0.16141*(33) + 0.26428*(55.5) - 0.56596*(1) +  0.34012*(2)
y4
```

```{r}
#Question 2
#Splitting into training and testing for "smoke" variable
set.seed(1234)
split=sample(2,nrow(Lungdata),replace = TRUE,prob = c(0.9,0.1))
training2=Lungdata[split==1, ]
testing2=Lungdata[split==2, ]
head(training2)
head(testing2)

```

```{r}
#2b
training2$Smoke <- factor(training2$Smoke)
mylogit <- glm( Smoke ~ LungCap + Age + Height + Gender, data = training2, family = "binomial")
summary(mylogit)
```
```{r}
#equation
#log(p/(1-p))=-11.50807-0.56167(LungCap)+0.25376(Age) + 0.16068(Height) -0.23360(Gender)

```


```{r}
#2c
#There are non-significant factor variables in this model which are Height and Gender. This is because the Smoke variable has no effect on the both Height and Gender, that is, its effect is statistically close to zero

```

```{r}
#2d: The validity of the model using testing data
prediction2 = predict( mylogit, testing, type ="response")
head(prediction2)

```

```{r}
#2e: Deriving equation for p based on equation on 2b
#let y = log(p/(1-p))

#then log(p/(1-p))=y

#p/(1-p) =exp(y)

#p =exp(-11.50807-0.56167(LungCap)+0.25376(Age) + 0.16068(Height) -0.23360(Gender))/(1+ exp(-11.50807-0.56167(LungCap)+0.25376(Age) + 0.16068(Height) -0.23360(Gender)))
```

```{r}


```

```{r}
#f. Gender = male, LungCap = 10, Height = 54, Age =40
#let p be the equation
p =exp(-11.50807-0.56167*(10)+0.25376*(40) + 0.16068*(54) -0.23360*(1))/(1+ exp(-11.50807-0.56167*(10)+0.25376*(40) + 0.16068*(54) -0.23360*(1)))
p
```

```{r}
#Gender = female, LungCap = 10, Height = 54, Age =40
#let q be the equation
q =exp(-11.50807-0.56167*(10)+0.25376*(40) + 0.16068*(54) -0.23360*(2))/(1+ exp(-11.50807-0.56167*(10)+0.25376*(40) + 0.16068*(54) -0.23360*(2)))
q
```

```{r}
#3a ANOVA, alpha =0.05
#Ho=> mean5 = mean10 = mean15 = mean 20
#H1=> There are differences in mean of the physical fitness of engineers
y5=c(56,55,61,59,60)
y10=c(64,61,50,57,55)
y15=c(45,46,45,39,43)
y20=c(42,39,45,43,41)
fitness=data.frame(y5,y10,y15,y20)
fitness
a<-stack(fitness)
names(a)<-c("pushups","timewithdepartment")
a
av1<-aov(pushups~timewithdepartment,data=a)
summary(av1)
```

```{r}
#Conclusion
# Since F Statistic is less than F Alpha,we reject our null hypothesis as the p-value is very low and conclude that there are differences in the physical fitness of engineers by time with the department group at alpha =0.05
```

```{r}
#3b
# Tukey HSD test:
Tukey_test =TukeyHSD(av1, conf.level =0.95)
Tukey_test
```

```{r}
#from the above results of TukeyHSD test, all the comparisons except y10-y5 and y20-y15 have  values of “p adj” < .05, we will conclude these two two group means may be different. They are statistically significant. On the other hand, y10-y5  and y20-y15 have a small difference between upper and lower, resulting in their p-value adjustment being greater than 0.05, hence showing they are both statistically non-significant.
```

```{r}

```

```{r}
#Question 4
#4a
League = c(rep("NFL",5),rep("AFL",5))
XDistance =c(14.5,24.5,34.5,44.5,52,14.5,24.5,34.5,44.5,52)
Success = c(68,74,61,38,2,62,49,43,25,7)
Attemps = c(77,95,113,138,38,67,70,79,82,24)
OddofSuccess =c((Success/Attemps)/(1-(Success/Attemps))) #value of (p/1-p)
print("odds of Success")
OddofSuccess
print("Y") #Y= log(p/1-p)
Y  =c(log10(OddofSuccess))
Y
```

```{r}
#creating table using OddofSuccess and Y rounded to 4 decimal places
OddofSuccess_rounded=c(7.5556,3.5238,1.1731,0.3800,0.0556,12.4000,2.3333,1.1944,0.4386,0.4118)
Y_rounded=c(0.8783,0.5470,0.0693,-0.4202,-1.2553, 1.0934,0.3680,0.0772,-0.3579,-0.3854)
Table4a =data.frame(League, XDistance, OddofSuccess_rounded, Y_rounded)
Table4a
```


```{r}
#4b
My_table =data.frame(XDistance, Y)
plot(My_table, cex =1, pch =20, col="blue", xlab="X=Distance", ylab="Y=log(p/(1-p))", main="Y versus X")
```
```{r}
#4c
#Fitting the model and adding line to scatterplot
My_model=lm(formula =Y~XDistance, data = My_table)
summary(My_model)
```
```{r}
plot(My_table, cex =1, pch =20, col="blue", xlab="X=Distance", ylab="Y=log(p/(1-p))", main="Y versus X")
abline(My_model, col ="red")
```

```{r}
#4d : SHow that p = e^y/(1+e^y)
# Y= B0+B1x

#log(p/(1-p))=Y

#log(p/(1-p))=B0+B1x

#p/(1-p)= e^(b0+B1x)

#p =(1-p)* e^(b0+B1x)

#p = e^(b0+B1x) -pe^(b0+B1x)

#p =e^(b0+B1x)/(1-e^(b0+B1x))

#substituting Y back into the equation

#p =e^y/1-e^Y  (SHOWN)


```

```{r}
#4e
#find the value of P when distance is 15 yards
P15 =exp(15)/(1-exp(15))
print("When distance is 15 yards")
P15

P50 =exp(50)/(1-exp(50))
print("When distance is 50 yards")
P50


```

```{r}
#4f
#Evaluating lim(x->0)  and lim(x->oo)
#**attached separately**

```

```{r}

```

```{r}

```

